// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/chains": {
            "get": {
                "description": "Returns list of chains for authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Get user chains",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID). Example: 123e4567-e89b-12d3-a456-426614174000",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of chains",
                        "schema": {
                            "$ref": "#/definitions/dto.GetChainsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/chains/{chain_id}": {
            "get": {
                "description": "Returns full chain details for the given chain_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Get chain by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain ID",
                        "name": "chain_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID). Example: 123e4567-e89b-12d3-a456-426614174000",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Chain details",
                        "schema": {
                            "$ref": "#/definitions/dto.ChainResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/chains/{chain_id}/decision": {
            "post": {
                "description": "Process accept or reject decision for a chain.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Process decision on chain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain ID",
                        "name": "chain_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID). Example: 123e4567-e89b-12d3-a456-426614174000",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Decision request. Example: {\\",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DecisionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response. Example: {\\\"chain_id\\\":\\\"123e4567-e89b-12d3-a456-426614174000\\\", \\\"status\\\":\\\"processed\\\", \\\"message\\\":\\\"Decision accepted\\\"}",
                        "schema": {
                            "$ref": "#/definitions/dto.DecisionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/offers": {
            "post": {
                "description": "Create a new offer (idempotent with Idempotency-Key header)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exchange"
                ],
                "summary": "Create exchange offer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID). Example: 123e4567-e89b-12d3-a456-426614174000",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Post exchange request. Example: {\\",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostExchangeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.PostExchangeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/offers/my": {
            "get": {
                "description": "Returns offers created by current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exchange"
                ],
                "summary": "Get my offers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID). Example: 123e4567-e89b-12d3-a456-426614174000",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of user offers",
                        "schema": {
                            "$ref": "#/definitions/dto.GetMyOffersResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":\\\"ok\\\"}",
                        "schema": {
                            "$ref": "#/definitions/health.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Attribute": {
            "type": "object",
            "required": [
                "attribute_id"
            ],
            "properties": {
                "attribute_id": {
                    "type": "string",
                    "example": "color"
                },
                "max_value": {
                    "description": "Для диапазонных фильтров (\"max_value\": 345)",
                    "type": "integer",
                    "example": 345
                },
                "min_value": {
                    "description": "Для диапазонных фильтров (\"min_value\": 65)",
                    "type": "integer",
                    "example": 65
                },
                "value": {
                    "description": "Добавлено для одиночных значений (\"value\": \"like_new\")",
                    "type": "string",
                    "example": "red"
                },
                "values": {
                    "description": "Для массивов (\"values\": [\"white\"])",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"white\"]"
                    ]
                }
            }
        },
        "dto.ChainInfoResponse": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "chain_length": {
                    "type": "integer",
                    "example": 2
                },
                "has_chain": {
                    "type": "boolean",
                    "example": true
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "user_action_required": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.ChainResponse": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "chain_length": {
                    "type": "integer",
                    "example": 3
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-08-09T12:00:00Z"
                },
                "expires_at": {
                    "type": "string",
                    "example": "2026-08-10T12:00:00Z"
                },
                "my_summary": {
                    "$ref": "#/definitions/dto.MySummaryResponse"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StepResponse"
                    }
                },
                "time_left_seconds": {
                    "type": "integer",
                    "example": 3600
                }
            }
        },
        "dto.DecisionRequest": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "accept",
                        "reject"
                    ],
                    "example": "accept"
                }
            }
        },
        "dto.DecisionResponse": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "message": {
                    "type": "string",
                    "example": "Decision accepted"
                },
                "status": {
                    "type": "string",
                    "example": "processed"
                }
            }
        },
        "dto.DesiredItemResponse": {
            "type": "object",
            "properties": {
                "allow_delivery": {
                    "type": "boolean",
                    "example": true
                },
                "category_id": {
                    "type": "string",
                    "example": "electronics"
                },
                "id": {
                    "type": "string",
                    "example": "desired-1"
                },
                "max_price": {
                    "type": "number",
                    "example": 3000
                },
                "min_price": {
                    "type": "number",
                    "example": 1000
                },
                "title_pattern": {
                    "type": "string",
                    "example": "camera"
                }
            }
        },
        "dto.GetChainsResponse": {
            "type": "object",
            "properties": {
                "chains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ChainResponse"
                    }
                }
            }
        },
        "dto.GetMyOffersResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OfferResponse"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.ItemResponse": {
            "type": "object",
            "properties": {
                "attributes": {},
                "category_id": {
                    "type": "string",
                    "example": "kids-bikes"
                },
                "description": {
                    "type": "string",
                    "example": "Small bike for 4-6 years old"
                },
                "id": {
                    "type": "string",
                    "example": "item-uuid-2"
                },
                "photo": {
                    "type": "string",
                    "example": "https://example.com/photos/2.jpg"
                },
                "title": {
                    "type": "string",
                    "example": "Child Bike"
                }
            }
        },
        "dto.ItemSummary": {
            "type": "object",
            "properties": {
                "attributes": {},
                "category_id": {
                    "type": "string",
                    "example": "home-decor"
                },
                "description": {
                    "type": "string",
                    "example": "A nice vintage lamp in working condition"
                },
                "estimated_price": {
                    "type": "number",
                    "example": 1999.99
                },
                "id": {
                    "type": "string",
                    "example": "item-uuid-1"
                },
                "photo": {
                    "type": "string",
                    "example": "https://example.com/photos/1.jpg"
                },
                "title": {
                    "type": "string",
                    "example": "Vintage Lamp"
                }
            }
        },
        "dto.MySummaryResponse": {
            "type": "object",
            "properties": {
                "giving_item": {
                    "$ref": "#/definitions/dto.ItemSummary"
                },
                "my_decision": {
                    "type": "string",
                    "example": "accept"
                },
                "receiving_item": {
                    "$ref": "#/definitions/dto.ReceivedItem"
                },
                "user_action_required": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.OfferResponse": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string",
                    "example": "electronics-vintage"
                },
                "chain_info": {
                    "$ref": "#/definitions/dto.ChainInfoResponse"
                },
                "city_name": {
                    "type": "string",
                    "example": "Moscow"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-08-09T12:00:00Z"
                },
                "delivery_enabled": {
                    "type": "boolean",
                    "example": false
                },
                "desired_item": {
                    "$ref": "#/definitions/dto.DesiredItemResponse"
                },
                "estimated_price": {
                    "type": "number",
                    "example": 2500
                },
                "item_status": {
                    "type": "string",
                    "example": "active"
                },
                "offered_item_id": {
                    "type": "string",
                    "example": "offer-1"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"https://example.com/photos/1.jpg\"]"
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "Vintage Camera"
                }
            }
        },
        "dto.OfferedItem": {
            "type": "object",
            "required": [
                "category_id",
                "title"
            ],
            "properties": {
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Attribute"
                    }
                },
                "category_id": {
                    "type": "string",
                    "example": "electronics-vintage"
                },
                "description": {
                    "type": "string",
                    "example": "Old film camera in working condition"
                },
                "estimated_price": {
                    "type": "integer",
                    "example": 2500
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"https://example.com/photos/1.jpg\"]"
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "Vintage Camera"
                }
            }
        },
        "dto.PostExchangeRequest": {
            "type": "object",
            "required": [
                "city_name",
                "offered_item",
                "wanted_item"
            ],
            "properties": {
                "city_name": {
                    "type": "string",
                    "example": "Moscow"
                },
                "delivery_enabled": {
                    "type": "boolean",
                    "example": false
                },
                "offered_item": {
                    "$ref": "#/definitions/dto.OfferedItem"
                },
                "wanted_item": {
                    "$ref": "#/definitions/dto.WantedItem"
                }
            }
        },
        "dto.PostExchangeResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-08-09T12:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "exchange-uuid-1"
                },
                "status": {
                    "type": "string",
                    "example": "created"
                }
            }
        },
        "dto.ReceivedItem": {
            "type": "object",
            "properties": {
                "attributes": {},
                "category_id": {
                    "type": "string",
                    "example": "home-decor"
                },
                "description": {
                    "type": "string",
                    "example": "A nice vintage lamp in working condition"
                },
                "estimated_price": {
                    "type": "number",
                    "example": 1999.99
                },
                "from_user": {
                    "$ref": "#/definitions/dto.UserSummary"
                },
                "id": {
                    "type": "string",
                    "example": "item-uuid-1"
                },
                "photo": {
                    "type": "string",
                    "example": "https://example.com/photos/1.jpg"
                },
                "title": {
                    "type": "string",
                    "example": "Vintage Lamp"
                }
            }
        },
        "dto.StepResponse": {
            "type": "object",
            "properties": {
                "from_user": {
                    "$ref": "#/definitions/dto.UserResponse"
                },
                "is_accepted": {
                    "type": "boolean",
                    "example": true
                },
                "item": {
                    "$ref": "#/definitions/dto.ItemResponse"
                },
                "step_order": {
                    "type": "integer",
                    "example": 1
                },
                "to_user": {
                    "$ref": "#/definitions/dto.UserResponse"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "id": {
                    "type": "string",
                    "example": "user-uuid-1"
                },
                "is_me": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Ivan Petrov"
                }
            }
        },
        "dto.UserSummary": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "id": {
                    "type": "string",
                    "example": "user-uuid-1"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan Petrov"
                }
            }
        },
        "dto.WantedItem": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Attribute"
                    }
                },
                "category_id": {
                    "type": "string",
                    "example": "electronics"
                },
                "max_price": {
                    "type": "integer",
                    "example": 3000
                },
                "min_price": {
                    "type": "integer",
                    "example": 1000
                },
                "title_query": {
                    "type": "string",
                    "example": "camera"
                }
            }
        },
        "health.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
